[build]
  command = ""
  publish = "out"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api?path=:splat"
  status = 200
